name: Build

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run build
        env:
            MORRISBOOK_TOKEN: ${{ secrets.MORRISBOOK_TOKEN }}
        run: npx @11ty/eleventy

      - name: Copy to hosting
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USER }}
          key: ${{ secrets.SCP_KEY }}
          source: _site
          target: crookmorris-test
          strip_components: 1
          rm: true
