name: Build

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22']

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npx @11ty/eleventy

      - name: Copy to Hostinger
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          source: _site
          target: incoming
          rm: true

      - name: Move replacement files into public_html
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: /home/u112729377/replace.sh

      - name: Copy to drawk.cab
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DRAWK_CAB_HOST }}
          username: www
          key: ${{ secrets.DRAWK_CAB_PRIVATE_KEY }}
          source: _site/*
          target: /var/www/crookmorris
          rm: true
